spring.profiles.group:
  "local": "kafka-dev,db-local,app-dev"
  "dev": "kafka-dev,db-dev,app-dev"
  "prod": "kafka-prod,db-prod,app-prod"

spring.cloud.stream:
  bindings:
    customer-event-0:
      destination: customer-event-topic
      producer:
        required-groups: auditGroup

  defaultBinder: kafka
  default.contentType: application/json
